kind: Deployment
apiVersion: apps/v1
metadata:
  name: chat-server
spec:
  selector:
    matchLabels:
      app: chat-server
  template:
    metadata:
      labels:
        app: chat-server
    spec:
      containers:
        - name: chat-server
          image: "raaaaaaaay86/spring-grpc-chat-server"
          imagePullPolicy: Never
          ports: # Just Informative
            - name: "spring"
              containerPort: 9090